spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/publishing-company'
    username: 'postgres'
    password: 'spira2002'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        show_sql: 'true'
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    format:
      date: yyyy-MM-dd
  # TODO: delete when deploy
  thymeleaf:
    cache: false
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080